services:
  nginx-hls-streamer:
    image: nginx:latest
    container_name: nginx-hls-streamer
    hostname: nginx-hls-streamer
    networks:
      - public
      - internal
    ports:
      - ${NGINX_HLS_STREAM_PORT}:80
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www:ro